name: Tom Scan
description: >
  Scan your code with Tom to detect bugs, vulnerabilities and code smells
  in more than 25 programming languages.
branding:
  icon: check
  color: green
runs:
  using: docker
  image: Dockerfile
inputs:
  args:
    description: Additional arguments to the tom scanner
    required: false
  projectBaseDir:
    description: Set the sonar.projectBaseDir analysis property
    required: false
    default: .
